### ISSUE TITLE
Module not found: 'firebase'

### ISSUE THREAD

**Issue by Skaronator** [SCasarotto/react_redux_aws_cognito#1]
You are using Firebase here: https://github.com/SCasarotto/react_redux_aws_cognito/blob/fbfe289dead8bf8f5e34a54cae7473a655c1b5b8/src/containers/App/App.js#L6
without defining in the package.json

**Comment by SCasarotto** [comment]
Ah, you are right. This was converted from an app that used firebase. I have just cleaned up some of the codebase and removed the Firebase reference. Sorry about that.
